language: go

env:
  - GO111MODULE=on

cache:
  directories:
    - $HOME/.cache/go-build
    - $HOME/gopath/pkg/mod

go:
  - "1.13.x"

git:
  depth: 1

install: true

script:
  - make coverage

after_success:
  - bash <(curl -s https://codecov.io/bash)
